SKB-LaTeX, v0.5 2010/08/04
--------------------------

*Create and maintain a repository for long-living documents*

This package provides  macros that help  to build a  document repository for
long living  documents. It  focuses on  structure and  re-use of text, code,
figures etc. The basic concept  is to first separate structure  from content
(i.e. text about  a topic from  the structure it  is presented by)  and then
separating the  content from  the actual  published document,  thus enabling
easy re-use  of text  blocks in  different publications  (i.e. text  about a
protocol in a short article about this  protocol as well as in a book  about
many protocols); all without constantly copying or changing text. As a  side
effect, using the document  classes provided, it hides  a lot of LaTeX  from
someone who just wants to write articles and books. 

The following classes are supported

- skbarticle: an article class using the memoir package
- skbbook: a book class using the memoir package
- skbbeamer: a class for presentations using the beamer package
- skblncsbeamer: a class for annotated slides using the beamer package
- skblncsppt: a class for annotated Powerpoint slides

The documentation (current/doc) provides for a user guide, the documentation
of  the  LaTeX  package  and  classes  and  a  few  documents  showing   the
capabilities  of  the  skb  package  for  documents  and  presentations. All
documentation of the  SKB is done  using the SKB  itself, so you  can have a
look into the LaTeX code as well to see how it works.


Status: Alpha, Experimental
---------------------------
This package, while being  used by me and  some early adaptors, is  still in
alpha status, thus experimental. We are using it to maintain a large  amount
of documents  (articles, lecture  notes, some  books, project documentation,
open source  documentation) and  various different  platforms (Windows  with
MikTeX, several Linux systems  and OSX). Since we  eat our own dog  food, we
are fairly confident that the package  does it's job well. However, this  is
not  written by a LaTeX expert, I am still  learning, and the package  might
or  might  not  be usefull  for you  and might  or might  not work  on your
machine.   We   are    very   interested   in   comments,   critic,  advice,
recommendations, complaints; as long as you try to keep them contructive ;)


Contents and Installation
-------------------------
Your LaTeX  distribution might  have the  skb package  already installed  or
might install it automatically when you are trying to use it the first time.
If you have  to manually install  it, copy the  files listed below  to their
respective  locations   within  your   LaTeX  distribution   (TSD  compliant
structure). Once you  copied all files,  please don't forget  to update your
filename database. To use  the skb package, you  probably only need to  copy
the  files from  the /run  folder. In  the directory  listing below,  please
substitute `texmf` with the root of your LaTeX distribution

[archive root]
 |
 +-- doc
 |    +-- skb.pdf           : texmf/doc/latex/skb
 |    +-- ug-slides-anim    : texmf/doc/latex/skb
 |    +-- ug-slides-noanim  : texmf/doc/latex/skb
 |    `-- ug-slides-notes   : texmf/doc/latex/skb
 +-- source
 |    +-- skb.dtx           : texmf/source/latex/skb
 |    `-- skb.ins           : texmf/source/latex/skb
 `-- run
      +-- skb.cfg           : texmf/tex/latex/skb
      +-- skb.sty           : texmf/tex/latex/skb
      +-- skbarticle.cls    : texmf/tex/latex/skb
      +-- skbbeamer.cls     : texmf/tex/latex/skb
      +-- skbbook.cls       : texmf/tex/latex/skb
      +-- skblncsbeamer.cls : texmf/tex/latex/skb
      `-- skblncsppt.cls    : texmf/tex/latex/skb

The   repository   contains   the  LaTeX   sources   of   the  skb   package
(`current/source`) and the  sources for the  documentation (`/current/doc`).
The distribution archive (download) also contains the generated LaTeX  files
(`/run`) and the generated PDF files of the documentation (`/doc`). You  can
reproduce them from  the source in  the repository (`current/source`)  using
the docstrip command and the ltxdoc package (assuming you are in the  folder
`/current`):

[source,shell]
----
  # cd run
  # latex ../skb.ins
  # cd ../doc
  # pdflatex ../skb.dtx
  # pdflatex ../skb.dtx
  # pdflatex ../skb.dtx
----

This will create   the style file   (`skb.sty`), the general   configuration
file (`skb.cfg`) and  the class files  (`*.cls`)  in the  directory /run and
the  package documentation in the directory /doc. You need to have docstrip,
ltxdoc  and  doc installed,  which  should be  already  part of  your  LaTeX
distribution. Parts of the documentation (the user guide) are in the  folder
doc/user-guide  and  you  will need  to  install  the SKB   before you  can
create the documentation   (in other words,  the SKB package  uses itself to
compile the PDF document).


Configuration
-------------
The SKB comes with a  default  configuration in the package  (`skb.sty`) and
an  external   configuration   file   (`skb.cfg`).   There   are    multiple
options   to  configure   the  SKB    (changing   the   coniguration   file,
using  a   local configuration  file  called  `skblocal.cfg` or  using   the
provided  macro `\skbconfig`). Please refer to the user guide for details.


Where do I get it?
------------------
- GitHub: https://github.com/vdmeer/skb-latex
- CTAN: http://www.ctan.org/tex-archive/macros/latex/contrib/skb/


License
-------
Copyright (c) 2010-2011 Sven van der Meer <sven@vandermeer.de>

This work may be distributed  and/or modified under the conditions  of the
LaTeX Project Public  License, either version  1.3 of this  license or (at
your option) any later version.
The latest version of this license is in
   <http://www.latex-project.org/lppl.txt>
and version 1.3  or later is  part of all  distributions of LaTeX  version
2005/12/01 or later.

This work has the LPPL maintenance status `author-maintained'.

The Current Maintainer of this work is
   Sven van der Meer <sven@vandermeer.de>

This software is  provided 'as is',  without warranty of  any kind, either
expressed  or  implied,  including,  but  not  limited  to,  the   implied
warranties of merchantability and fitness for a particular purpose.

This work consists of all files in source/MANIFEST.TXT.